ShopMohinh/Areas/Admin/Controllers/RoleManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopMohinh.Models;

namespace ShopMohinh.Areas.Admin.Controllers
{

    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class RoleManagerController : Controller
    {

        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public RoleManagerController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();

            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName) // thêm vai trò 
        {
            if(!string.IsNullOrEmpty(roleName))
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim())); // Trim để tránh trường hợp người ta nhập nhiều khoảng trắng, trim cắt khoảng trắng
            }
            return RedirectToAction("Index");
        }
    }
}

ShopMohinh/Areas/Admin/Views/RoleManager/Index.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Quản lý vai trò";
 
}

<h1>Quản lý vai trò</h1>
<form method="post" asp-action="AddRole" asp-controller="RoleManager">
    <div class="input-group">
        <input name="roleName" class="form-control w-25">
        <span class="input-group-btn">
            <button class="btn btn-info">Thêm vai trò mới</button>
        </span>
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>

            <th>Id</th>
            <th>Vai trò</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
            </tr>
        }

    </tbody>
</table>